// Exporter: Creates downloadable Roblox starter packs
import JSZip from 'jszip';

export interface ExportConfig {
  trackSlug: string;
  moduleTitle: string;
  lessonTitle: string;
  scripts: Array<{
    name: string;
    content: string;
    location: 'StarterPlayerScripts' | 'ServerScriptService' | 'ReplicatedStorage';
  }>;
  readme?: string;
}

/**
 * Generates a ZIP file containing starter scripts and README for Roblox Studio
 */
export async function generateStarterPack(config: ExportConfig): Promise<Blob> {
  const zip = new JSZip();

  // Add README
  const readme = config.readme || generateDefaultReadme(config);
  zip.file('README.md', readme);

  // Add scripts
  for (const script of config.scripts) {
    const path = getScriptPath(script);
    zip.file(path, script.content);
  }

  // Add a simple .rbxmx template (XML format)
  // Note: This is a simplified version. In production, you'd generate proper Roblox XML
  const rbxmx = generateRobloxModel(config);
  zip.file(`${config.trackSlug}-${sanitizeFilename(config.moduleTitle)}.rbxmx`, rbxmx);

  // Generate ZIP
  return await zip.generateAsync({ type: 'blob' });
}

function getScriptPath(script: { name: string; location: string }): string {
  const base = 'Scripts/';
  const sanitized = sanitizeFilename(script.name);
  
  switch (script.location) {
    case 'StarterPlayerScripts':
      return `${base}StarterPlayer/StarterPlayerScripts/${sanitized}.lua`;
    case 'ServerScriptService':
      return `${base}ServerScriptService/${sanitized}.lua`;
    case 'ReplicatedStorage':
      return `${base}ReplicatedStorage/${sanitized}.lua`;
    default:
      return `${base}${sanitized}.lua`;
  }
}

function sanitizeFilename(name: string): string {
  return name.replace(/[^a-z0-9_-]/gi, '_');
}

function generateDefaultReadme(config: ExportConfig): string {
  return `# ${config.lessonTitle} - Starter Pack

## About
This starter pack contains scripts and resources for the "${config.lessonTitle}" lesson from the ${config.moduleTitle} module.

## Installation

### Method 1: Direct Script Import
1. Open Roblox Studio
2. Open your place/game
3. Navigate to the appropriate location in the Explorer:
   - **StarterPlayer > StarterPlayerScripts** for client scripts
   - **ServerScriptService** for server scripts
   - **ReplicatedStorage** for shared modules
4. Right-click and select "Insert Object" > "Script" or "LocalScript"
5. Copy the code from the \`.lua\` files in this pack
6. Paste into the appropriate scripts in Studio

### Method 2: Drag & Drop (if supported)
1. Extract all files from this ZIP
2. In Roblox Studio, try dragging the .rbxmx file directly into your game
3. Follow any prompts to place the scripts

## Folder Structure
\`\`\`
Scripts/
  ├── StarterPlayer/
  │   └── StarterPlayerScripts/  (Client-side scripts)
  ├── ServerScriptService/       (Server-side scripts)
  └── ReplicatedStorage/         (Shared modules)
\`\`\`

## Next Steps
1. Read through each script to understand the starter code
2. Complete the challenges in LearnRBX
3. Test your changes in Roblox Studio
4. Experiment and build upon the foundation

## Support
Visit LearnRBX for more lessons and challenges!

---
*Generated by LearnRBX - Master Roblox scripting with hands-on lessons*
`;
}

function generateRobloxModel(config: ExportConfig): string {
  // Simplified Roblox XML model format
  // In production, this would generate proper Roblox instance hierarchy
  return `<roblox version="4">
  <Item class="Folder" referent="RBX0">
    <Properties>
      <string name="Name">${config.moduleTitle}</string>
    </Properties>
    ${config.scripts
      .map(
        (script, idx) => `
    <Item class="${script.location === 'StarterPlayerScripts' ? 'LocalScript' : 'Script'}" referent="RBX${idx + 1}">
      <Properties>
        <string name="Name">${script.name}</string>
        <ProtectedString name="Source"><![CDATA[${script.content}]]></ProtectedString>
      </Properties>
    </Item>`
      )
      .join('\n')}
  </Item>
</roblox>`;
}

/**
 * Creates a starter pack for a specific lesson
 */
export async function createLessonExport(
  lessonSlug: string,
  starterCode: string
): Promise<Blob> {
  const config: ExportConfig = {
    trackSlug: 'lesson-export',
    moduleTitle: 'Practice',
    lessonTitle: lessonSlug,
    scripts: [
      {
        name: lessonSlug,
        content: starterCode,
        location: 'StarterPlayerScripts',
      },
    ],
  };

  return generateStarterPack(config);
}

